# Generated by Django 3.2.4 on 2021-06-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_region_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='lf_group',
        ),
        migrations.RemoveField(
            model_name='lifecyclestage',
            name='group',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='lf_stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.lifecyclestage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifecyclestage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.lifecyclestage'),
        ),
        migrations.DeleteModel(
            name='LifeCycleGroup',
        ),
    ]
